project:
  type: website
  output-dir: "../"

website:
  title: "The Kinz-Thompson Lab"

  navbar:
    background: secondary
    search: true
    left:
      - text: Home
        file: index.qmd
        # text: Home
    
      - people.qmd
      - research.qmd
      - publications.qmd
      - software.qmd

      # - section: "Posts"
      #   contents:
      #     - about.qmd

      - resources.qmd
      - contact.qmd

format:
  html:
    theme: lux
    # toc: true



